name: fluentd
version: 0.1.0
appVersion: 1.2.4
description: A Fluentd Helm chart for Kubernetes.
keywords: 
  - logging
  - elasticsearch 
  - s3 
  - docker 
  - fluentd 
  - kubernetes 
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
sources:
  - https://www.fluentd.org/
maintainers:
  - name: dstorck
    email: deirdre.storck@gmail.com