name: fluentd
version: 0.1.4
appVersion: 1.2.4
description: A Fluentd Helm chart for Kubernetes.
keywords:
- logging
- elasticsearch
- s3
- docker
- fluentd
- kubernetes
home: https://github.com/samsung-cnct/chart-fluentd
sources:
- https://www.fluentd.org/
- https://github.com/samsung-cnct/chart-fluentd
maintainers:
- name: Samsung CNCT OSS Maintainers
  email: oss-maintainer@samsung-cnct.io
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
engine: gotpl
